languageCode = "en-us"
title = "Simon Nyberg"
baseURL = "http://blog.nyberg.io"
theme = "hucore"
publishDir = "docs"

[params]
description = "Simon Nybergs blog"
keywords = ["blog"]
author = "Simon Nyberg"
sharingicons = true

[params.highlight]
style = "github"
languages = ["javascript"]

[[params.social]]
url = "https://github.com/siimon"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/siimon_nyberg"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/simon--nyberg"
fa_icon = "fa-linkedin-square"
